### ISSUE TITLE
Win10系统下仍然无法运行问题

### ISSUE THREAD

**Issue by xiaoyang212** [zkeyoung/Easy-Share#1]
1.1版本较1.0版本安装过程中更加丝滑，同时也增加了桌面图标，方便了使用，但无论是点击图标还是找到源文件、cmd
、管理员方式还是无法运行，但在任务管理器中存在该程序的进程。
![1ceeb7868230ae30cac4c0e9cf3da2a](https://user-images.githubusercontent.com/83319298/224471402-0328591f-110f-4227-bd05-e633c0f6c569.png)

**Comment by zkeyoung** [comment]
已修复
