### ISSUE TITLE
消息通知功能每次弹出重复通知次数太多

### ISSUE THREAD

**Issue by xiaoyang212** [zkeyoung/Easy-Share#2]
当对方下载分享的文件时，不停弹出通知
![O}AHS884@QI0U~L F@ZJ}`E](https://user-images.githubusercontent.com/83319298/224895699-327af643-4bd4-4a85-8542-dd0777707d06.png)

**Comment by zkeyoung** [comment]
分享文件每次被下载都会通知一次。
